// https://projects.neoforged.net/
plugins {
    id 'eclipse'
    id 'net.neoforged.moddev' version '2.0.107'
}

version = '1.1.1+1.21.1'
group = 'net.enderturret'
base {
    archivesName = 'MinestuckCompat'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)
java.withSourcesJar()

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven { url = "https://maven.createmod.net" } // Create, Ponder, Flywheel
    maven { url = "https://maven.ithundxr.dev/snapshots" } // Registrate
    maven {
        url = 'https://api.modrinth.com/maven'
        content {
            includeGroup 'maven.modrinth'
        }
    }
    maven {
        name = 'ModMaven'
        url = 'https://modmaven.dev'
        content { // This maven is really slow, so only include the mods we need from it
            includeGroup 'mezz.jei'
            includeGroup 'mekanism'
        }
    }
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    // These mods need to be obtained manually and placed in /libs
    implementation "com.mraof:Minestuck-1.21.1:${minestuck_version}"
    runtimeOnly "net.commoble:infiniverse-1.21:${infiniverse_version}"
    implementation "com.supermartijn642:rechiseled:${rechiseled_version}"

    implementation "maven.modrinth:ae2:${ae2_version}"
    implementation "maven.modrinth:applied-mekanistics:${applied_mekanistics_version}"
    implementation "maven.modrinth:biomes-o-plenty:${biomesoplenty_version}"
    implementation "maven.modrinth:farmers-delight:${farmers_delight_version}"
    implementation "maven.modrinth:immersiveengineering:${immersiveengineering_version}"

    implementation "mekanism:Mekanism:1.21.1-${mekanism_version}"
    implementation "mekanism:Mekanism:1.21.1-${mekanism_version}:generators"
    implementation "mekanism:Mekanism:1.21.1-${mekanism_version}:tools"

    compileOnly "mezz.jei:jei-1.21.1-common-api:${jei_version}"
    compileOnly "mezz.jei:jei-1.21.1-neoforge-api:${jei_version}"

    implementation ("com.simibubi.create:create-1.21.1:${create_version}:slim") { transitive = false }

    runtimeOnly "maven.modrinth:geckolib:${geckolib_version}"
    runtimeOnly "maven.modrinth:fusion-connected-textures:${fusion_version}"
    runtimeOnly "maven.modrinth:supermartijn642s-config-lib:${supermartijn_config_lib_version}"
    runtimeOnly "maven.modrinth:supermartijn642s-core-lib:${supermartijn_core_lib_version}"
    runtimeOnly "maven.modrinth:guideme:${guideme_version}"
    runtimeOnly "net.createmod.ponder:Ponder-NeoForge-1.21.1:${ponder_version}"
    runtimeOnly "dev.engine-room.flywheel:flywheel-neoforge-1.21.1:${flywheel_version}"
    implementation "com.tterrag.registrate:Registrate:${registrate_version}"
    runtimeOnly "maven.modrinth:terrablender:${terrablender_version}"
    runtimeOnly "maven.modrinth:glitchcore:${glitchcore_version}"
}

neoForge {
    version = '21.1.203'

    mods {
        minestuckcompat {
            sourceSet sourceSets.main
        }
    }

    parchment {
        // https://parchmentmc.org/docs/getting-started
        // https://ldtteam.jfrog.io/ui/native/parchmentmc-public/org/parchmentmc/data/
        minecraftVersion = '1.21.1'
        mappingsVersion = '2024.11.17'
    }

    runs {
        client {
            client()
            ideName = 'runMinestuckCompatClient'
            systemProperty('foxfilter.dev', 'true')
        }

        server {
            server()
            ideName = 'runMinestuckCompatServer'
        }

        data {
            data()
            ideName = 'runMinestuckCompatData'
            programArguments.addAll '--mod', 'minestuckcompat', '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
            systemProperty('minestuckcompat.datagen', 'true')
        }
    }
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
            'Specification-Title': 'Minestuck Compat',
            'Specification-Vendor': 'EnderTurret',
            'Specification-Version': '1',
            'Implementation-Title': project.name,
            'Implementation-Version': "${version}",
            'Implementation-Vendor' :'EnderTurret'
        ])
    }

    exclude '.cache'
    exclude 'net/enderturret/minestuckcompat/data/**'
    exclude 'net/enderturret/minestuckcompat/mixin/perf/small_grist_set/data/**'
}

tasks.named('sourcesJar', Jar).configure {
    exclude '.cache'
    exclude 'net/enderturret/minestuckcompat/data/**'
    exclude 'data/minestuckcompat/recipe/**'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

tasks.withType(AbstractArchiveTask).configureEach {
    preserveFileTimestamps = false
    reproducibleFileOrder = true
}

tasks.named('processResources', ProcessResources).configure {
    doLast {
        fileTree(dir: outputs.files.asPath, include: '**/*.json').each {
            File file -> file.text = groovy.json.JsonOutput.toJson(new groovy.json.JsonSlurper().parse(file))
        }
    }
}