org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

minestuck_version=1.14.0.0
infiniverse_version=2.0.1.0
# 4.8.4
geckolib_version=gFmrC8Ru
jei_version=19.27.0.340

ae2_version=19.2.17
guideme_version=21.1.15
applied_mekanistics_version=1.6.3

# 21.1.0.13
biomesoplenty_version=8vIRXPpR
# 4.1.0.8
terrablender_version=6e8GCrLb
# 2.1.0.0
glitchcore_version=8wmCpbQ2

mekanism_version=10.7.19.85
farmers_delight_version=1.21.1-1.3.2
immersiveengineering_version=12.4.2-194

quark_version=4.1-479
zeta_version=1.1-40

create_version=6.0.10-281
ponder_version=1.0.82+mc1.21.1
flywheel_version=1.0.6
registrate_version=MC1.21-1.3.0+67

rechiseled_version=1.2.3-neoforge-mc1.21
fusion_version=1.2.12-neoforge-mc1.21.1
supermartijn_config_lib_version=1.1.8-neoforge-mc1.21
supermartijn_core_lib_version=1.1.21-neoforge-mc1.21

extradelight_version=2.6.5

gtceu_version=1.21.1-7.0.2