modLoader="javafml"
loaderVersion="[1,)"
license="LGPL v2.1"
[[mods]]
    modId="minestuckcompat"
    displayName="Minestuck Compat"
    description='''
    A comprehensive Minestuck addon that provides grist costs and combination recipes for:
    * Applied Energistics 2
    * Biomes O' Plenty
    * Create
    * Farmer's Delight
    * Immersive Engineering
    * Mekanism
    * Minestuck (its trees)
    * Rechiseled
    * Supplementaries
    * Vanilla (trims, sherds, 1.21.1 content, among other things)

    Also includes recipe interpreters (for use with the grist cost generator) for:
    * Applied Energistics 2
    * Create
    * Immersive Engineering
    * Mekanism

    Additionally, it also includes partial (or full) grist cost support for:
    * Applied Mekanistics
    * Builders Crafts & Additions 2
    * Create Ore Excavation
    * Dank Storage
    * Expanded Storage
    * FramedBlocks
    * GraveStone Mod
    * Hostile Neural Networks
    * Lootr
    '''
    version="${file.jarVersion}"
    authors="EnderTurret"

[[mixins]]
    config="mixins.minestuckcompat.json"

[[dependencies.minestuckcompat]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,21.2)"
    ordering="NONE"
    side="BOTH"

[[dependencies.minestuckcompat]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,1.21.2)"
    ordering="NONE"
    side="BOTH"

[[dependencies.minestuckcompat]]
    modId="minestuck"
    type="required"
    versionRange="[1.21.1-1.13.1.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.minestuckcompat]]
    modId="extrastuck"
    type="optional"
    ordering="AFTER"
    reason="Extrastuck's Create integration conflicts with Minestuck Compat's."

[[dependencies.minestuckcompat]]
    modId="minestuck_extended"
    type="optional"
    ordering="AFTER"
    reason="Minestuck Extended's Farmers Delight et al. integration conflicts with Minestuck Compat's."